function h10_eqn = h10_eqn(L1,L7,theta3)
%H10_EQN
%    H10_EQN = H10_EQN(L1,L7,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Oct-2018 17:33:26

t2 = cos(theta3);
t3 = sin(theta3);
h10_eqn = [0.0;(L1.*7.493993263921922e19+L7.*t2.*7.493993263921922e19-L7.*t3.*5.231627888410998e19+3.662139521887698e18)./(L1.*1.154436750835558e17+L7.*t2.*1.154436750835558e17+L7.*t3.*3.31029411452487e16-2.317205880167409e15)-4.797542860019859e2];
