function h13_eqn = h13_eqn(L4,L9,theta3)
%H13_EQN
%    H13_EQN = H13_EQN(L4,L9,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Oct-2018 17:07:43

t2 = cos(theta3);
t3 = sin(theta3);
h13_eqn = [0.0;(L4.*6.133706977634152e18+L9.*t2.*6.133706977634152e18+L9.*t3.*1.01590987903474e19+7.111369153243182e17)./(L4.*1.576952828265726e16+L9.*t2.*1.576952828265726e16+L9.*t3.*2.7805933092777e15+1.94641531649439e14)-4.873995693270018e2];
