function h2_eqn = h2_eqn(L1,L2,theta1)
%H2_EQN
%    H2_EQN = H2_EQN(L1,L2,THETA1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Oct-2018 17:33:02

t2 = cos(theta1);
t3 = sin(theta1);
h2_eqn = [0.0;(L1.*7.493993263921922e19+L2.*t2.*7.493993263921922e19-L2.*t3.*5.231627888410998e19+3.662139521887698e18)./(L1.*1.154436750835558e17+L2.*t2.*1.154436750835558e17+L2.*t3.*3.31029411452487e16-2.317205880167409e15)-4.797542860019859e2];
