function h6_eqn = h6_eqn(L4,L5,theta1)
%H6_EQN
%    H6_EQN = H6_EQN(L4,L5,THETA1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Oct-2018 17:07:15

t2 = cos(theta1);
t3 = sin(theta1);
h6_eqn = [0.0;(L4.*5.940034830201899e18+L5.*t2.*5.940034830201899e18+L5.*t3.*1.011975864491736e19+7.083831051442151e17)./(L4.*1.576952828265726e16+L5.*t2.*1.576952828265726e16+L5.*t3.*2.7805933092777e15+1.94641531649439e14)-4.750618649128349e2];
