function h9_eqn = h9_eqn(L1,L7,theta3)
%H9_EQN
%    H9_EQN = H9_EQN(L1,L7,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Oct-2018 17:33:25

t2 = cos(theta3);
t3 = sin(theta3);
h9_eqn = [0.0;(L1.*7.58692698884342e19+L7.*t2.*7.58692698884342e19-L7.*t3.*5.22724259375581e19+3.659069815629067e18)./(L1.*1.154436750835558e17+L7.*t2.*1.154436750835558e17+L7.*t3.*3.31029411452487e16-2.317205880167409e15)-4.872934537130378e2];
