function predict_eq = state_predict_function(T,ddphi_body,ddpsi_body,ddtheta1,ddtheta2,ddtheta3,ddtheta4,ddtheta_body,dphi_body,dpsi_body,dtheta1,dtheta2,dtheta3,dtheta4,dtheta_body,phi_body,psi_body,theta1,theta2,theta3,theta4,theta_body)
%STATE_PREDICT_FUNCTION
%    PREDICT_EQ = STATE_PREDICT_FUNCTION(T,DDPHI_BODY,DDPSI_BODY,DDTHETA1,DDTHETA2,DDTHETA3,DDTHETA4,DDTHETA_BODY,DPHI_BODY,DPSI_BODY,DTHETA1,DTHETA2,DTHETA3,DTHETA4,DTHETA_BODY,PHI_BODY,PSI_BODY,THETA1,THETA2,THETA3,THETA4,THETA_BODY)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    22-Oct-2018 17:32:57

predict_eq = [ddphi_body;ddtheta_body;ddpsi_body;ddtheta1;ddtheta2;ddtheta3;ddtheta4;dphi_body+T.*ddphi_body;dtheta_body+T.*ddtheta_body;dpsi_body+T.*ddpsi_body;dtheta1+T.*ddtheta1;dtheta2+T.*ddtheta2;dtheta3+T.*ddtheta3;dtheta4+T.*ddtheta4;phi_body+T.*dphi_body;theta_body+T.*dtheta_body;psi_body+T.*dpsi_body;theta1+T.*dtheta1;theta2+T.*dtheta2;theta3+T.*dtheta3;theta4+T.*dtheta4];
